# Generated by Django 4.2.23 on 2025-08-14 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinesweeperGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('mines', models.PositiveIntegerField()),
                ('board_state', models.JSONField(default=dict)),
                ('revealed_cells', models.JSONField(default=list)),
                ('flagged_cells', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('won', 'Won'), ('lost', 'Lost')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minesweeper_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
