# Generated by Django 4.2.23 on 2025-08-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minesweepergame',
            name='board_state',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='minesweepergame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
