# Generated by Django 4.2.23 on 2025-08-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_minesweepergame_board_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minesweepergame',
            name='flagged_cells',
        ),
        migrations.RemoveField(
            model_name='minesweepergame',
            name='revealed_cells',
        ),
    ]
